import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Panzabi.com</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.mains}>
        <div className={styles.description}>
          <div>
            <a
              href="https://panzabi.com"
              target="_blank"
              rel="noopener noreferrer"
            >
              Panzabi.com{' '}
              <Image
                src="https://panzabi.com/wp-content/uploads/2020/11/cropped-panjabi-logo-300x64.png"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>
        <iframe
          src="https://panzabi.com"
          style={{ height: 'calc(100vh - 10px)', width: '100%' }}
          id="audio"
        />
      </main>
    </>
  );
}
