import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';

import Box from '@mui/material/Box';
import { DataGrid } from '@mui/x-data-grid';
import MainLayout from '@/layouts/mainLayout';
import Typography from '@mui/material/Typography';
import CircularProgress from '@mui/material/CircularProgress';
import Link from 'next/link';
import axios, { BASE_URL } from '@/axios';
import { useRouter } from 'next/router';
import React from 'react';
import OrderActions from '@/components/header/OrdersActions';
import useSWR from 'swr';

const fetcher = (path = '') =>
  fetch(`${BASE_URL}/${path}`).then((res) => res.json());

export default function Order() {
  const [orders, setOrders] = React.useState([]);
  const [rowId, setRowId] = React.useState();
  const { data, error, isLoading } = useSWR(`orders`, fetcher);

  // const { isFallback } = useRouter();
  // React.useEffect(() => {
  //   axios
  //     .get('orders')
  //     .then(({ data }) => setOrders(data))
  //     .catch((e) => {
  //       alert(e?.data?.response?.message);
  //       console.log(e);
  //     });
  // }, []);
  if (isLoading) {
    return (
      <Box
        sx={{
          display: 'flex',
          height: '90vh',
          justifyContent: 'center',
          alignItems: 'center',
        }}
      >
        <CircularProgress />
      </Box>
    );
  }
  const columns = [
    { field: '_id', flex: 0.35, headerName: 'ID', hide: true },
    {
      field: 'order_no',
      flex: 0.3,
      headerName: 'Order No',
      editable: true,
    },
    {
      field: 'delivery_date',
      type: 'dateTime',
      flex: 1,
      headerName: 'Delivery Date',
      // editable: true,
    },
    {
      field: 'quantity',
      type: 'number',
      flex: 0.3,
      headerName: 'Quantity',
      editable: true,
    },
    {
      field: 'price',
      type: 'number',
      flex: 0.2,
      headerName: 'Price',
      editable: true,
    },
    {
      field: 'discount',
      type: 'number',
      flex: 0.25,
      headerName: 'Discount',
      editable: true,
    },
    {
      field: 'due',
      type: 'number',
      flex: 0.2,
      headerName: 'Due',
      editable: true,
    },
    {
      field: 'status',
      flex: 0.35,
      headerName: 'Status',
      headerAlign: 'center',
      type: 'singleSelect',
      editable: true,
      valueOptions: [
        'PROCESSING',
        'ALTER',
        'COMPLETED',
        'DELIVERED',
        'TRAIL',
        'RETURN',
      ],
    },
    {
      field: 'order_type',
      flex: 0.35,
      headerName: 'Order Type',
      editable: true,
      type: 'singleSelect',
      valueOptions: ['READYMADE', 'TAILORS'],
    },
    {
      field: 'delivery_details',

      flex: 0.6,
      headerName: 'Customer/Delivery Details',
      editable: true,
    },
    {
      field: 'order_date',
      type: 'dateTime',
      flex: 1,
      headerName: 'Order Date',
      // editable: true,
    },

    {
      field: 'Actions',
      flex: 0.4,
      headerName: 'Actions',
      editable: true,
      renderCell: ({ row }) => {
        return <OrderActions {...{ row, rowId, setRowId }} />;
      },
    },
  ];

  return (
    <>
      <Head>
        <title>Panzabi.com</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/png" href="/favicon.png" />
      </Head>
      <MainLayout>
        <Box sx={{ width: '100%' }}>
          <Box sx={{ width: '100%' }}>
            <DataGrid
              loading={isLoading}
              autoHeight
              rows={Array.isArray(data) ? data : []}
              columns={columns}
              getRowId={(row) => row._id}
            />
          </Box>
        </Box>
      </MainLayout>
    </>
  );
}

// export const getStaticProps = async () => {
//   const { data } = await axios.get('orders');
//   return {
//     props: { orders: data },
//   };
// };
