import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';

import Box from '@mui/material/Box';
import { DataGrid } from '@mui/x-data-grid';
import MainLayout from '@/layouts/mainLayout';
import moment from 'moment';
import { Typography } from '@mui/material';
import Link from 'next/link';
import axios from '@/axios';

export default function Order({ orders }) {
  // console.log(orders);
  return (
    <>
      <Head>
        <title>Panzabi.com</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/png" href="/favicon.png" />
      </Head>
      <MainLayout>
        <Box sx={{ width: '100%' }}>
          <Box sx={{ width: '100%' }}>
            <DataGrid
              autoHeight
              rows={orders}
              columns={[
                { field: '_id', flex: 0.35, headerName: 'ID', hide: true },
                {
                  field: 'order_no',
                  flex: 0.3,
                  headerName: 'Order No',
                  editable: true,
                },
                {
                  field: 'delivery_date',
                  type: 'dateTime',
                  flex: 1,
                  headerName: 'Delivery Date',
                  // editable: true,
                },
                {
                  field: 'quantity',
                  type: 'number',
                  flex: 0.3,
                  headerName: 'Quantity',
                  editable: true,
                },
                {
                  field: 'price',
                  type: 'number',
                  flex: 0.2,
                  headerName: 'Price',
                  editable: true,
                },
                {
                  field: 'discount',
                  type: 'number',
                  flex: 0.25,
                  headerName: 'Discount',
                  editable: true,
                },
                {
                  field: 'due',
                  type: 'number',
                  flex: 0.2,
                  headerName: 'Due',
                  editable: true,
                },
                {
                  field: 'status',
                  flex: 0.35,
                  headerName: 'Status',
                  headerAlign: 'center',
                  type: 'singleSelect',
                  editable: true,
                  valueOptions: [
                    'PROCESSING',
                    'ALTER',
                    'COMPLETED',
                    'DELIVERED',
                    'TRAIL',
                    'RETURN',
                  ],
                },
                {
                  field: 'order_type',
                  flex: 0.35,
                  headerName: 'Order Type',
                  editable: true,
                  type: 'singleSelect',
                  valueOptions: ['READYMADE', 'TAILORS'],
                },
                {
                  field: 'delivery_details',

                  flex: 0.6,
                  headerName: 'Customer/Delivery Details',
                  editable: true,
                },
                {
                  field: 'order_date',
                  type: 'dateTime',
                  flex: 1,
                  headerName: 'Order Date',
                  // editable: true,
                },

                {
                  field: 'Actions',
                  flex: 0.4,
                  headerName: 'Actions',
                  editable: true,
                  renderCell: ({ row }) => {
                    return (
                      <Box>
                        <Typography>
                          <Link href={`/orders/${row._id}`} passHref>
                            <a rel="noopener noreferrer" target="_blank">
                              View
                            </a>
                          </Link>
                        </Typography>
                      </Box>
                    );
                  },
                },
              ]}
              getRowId={(row) => row._id}
            />
          </Box>
        </Box>
      </MainLayout>
    </>
  );
}

export const getStaticProps = async () => {
  const { data } = await axios.get('orders');
  return {
    props: { orders: data },
  };
};
